---
# handlers file for python
- name: remove {{ temp_dir_for_files_in_target_machine  }} directory
  ansible.builtin.file:
      path: "{{ temp_dir_for_files_in_target_machine  }}"
      state: absent
