---
- hosts: "{{host}}"
  gather_facts: False
  vars:
    - temp_dir_for_files_in_target_machine: /home/pi/for_rpi
    - dir_path_of_dependency_files_in_control_server: /home/ngsharna/for_rpi
    - installation_path: /opt/opencv_4.5.5

  roles:
     - opencv
 